# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wa-HdTY0eVjLKeNHEjSqAZlL0OfJ5pOe
"""

import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.datasets import load_iris
dataset=load_iris()
print(dataset.DESCR)

x=dataset.data
y=dataset.target
y

x

plt.plot(x[:,0][y==0]*x[:,1][y==0],x[:,1][y==0]*x[:,2][y==0],'r.',label="setosa")
plt.plot(x[:,0][y==1]*x[:,1][y==1],x[:,1][y==1]*x[:,2][y==1],'b.',label="Versicolour")
plt.plot(x[:,0][y==2]*x[:,1][y==2],x[:,1][y==2]*x[:,2][y==2],'y.',label="virginica")
plt.legend()
plt.show

import sklearn.preprocessing import standardscaler
x= standardscaler().fit_transform(x)

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y)

from sklearn.linear_model import logistic_regression_path

log_reg=logistic_regression_path

log_reg.fit(x_train,y_train)

log_reg.score(x,y)

log_reg.score(x_train,y_train)

log_reg,score(x_test,y_test)

"""# New Section"""